const AMBIENT_GIT_VARS = [
  "GIT_DIR",
  "GIT_WORK_TREE",
  "GIT_INDEX_FILE",
  "GIT_OBJECT_DIRECTORY",
  "GIT_ALTERNATE_OBJECT_DIRECTORIES",
  "GIT_COMMON_DIR",
  "GIT_PREFIX",
  "GIT_CONFIG_PARAMETERS",
] as const;

for (const key of AMBIENT_GIT_VARS) {
  delete process.env[key];
}
