{{- if and .Values.mikan.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mikan.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mikan.labels" . | nindent 4 }}
{{- end }}
